[package]
name = "chillffi"
version = "0.2.0"
edition = "2024"

#
authors = ["miruji <miruji@protonmail.com>"]
description = "A simple isolated dynamic FFI framework for Rust"
license-file = "LICENSE.md" # FCL
readme = "README.md"

# ======================================================================================================================

# For publish test:
# cargo publish --dry-run
# cargo package --list

repository = "https://github.com/rts-lang/chillffi"
keywords = ["ffi", "zygote", "ipc", "sandbox", "fork"]
categories = ["external-ffi-bindings", "os::unix-apis", "api-bindings"]
publish = true

include = [
  "src/**/*",
  "Cargo.toml",
  "README.md",
  "LICENSE.md",
]

documentation = "https://docs.rs/chillffi"
[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu", "aarch64-unknown-linux-gnu"]

# ======================================================================================================================

autobins = false
autoexamples = false
autotests = false
autobenches = false

# ======================================================================================================================

# Building as a cdylib is not provided. Works only in Rust.

# ======================================================================================================================

[profile.release]
opt-level = 3
codegen-units = 1
lto = "fat"
panic = "abort"
strip = "symbols"
overflow-checks = false
debug  = false
incremental = false
rpath = false

[profile.dev]
opt-level = 0
debug = true
overflow-checks = true
lto = false
incremental = true

# ======================================================================================================================

[dependencies]
bincode = { version = "2.0.1", features = ["serde"] }
# Used for FFI; (3.0 if anything - no).

libloading = { version = "0.9.0" }
# Used for dynamic library loading (libraryPath)
# and obtaining pointers to functions (methodName), which are then called.

libffi = { version = "5.2.0" }
# Provides dynamic calling of C functions with arbitrary signatures
# (number and types of arguments, return type) at runtime.
# Unlike statically hardcoded wrappers, libffi allows constructing
# a call on the fly based on a type description, which is good for FFI.

libc = { version = "1.0.0-alpha.4" }
# Provides the dup2/dup system calls for temporary
# redirection of stdout → stderr, isolating the library output from the service channel.

serde = { version = "1.0.229", features = ["derive"] }
# Serialization and deserialization of request and response structures.

ctor = "1.0.13"
# Execution of functions at process startup for automatic initialization.

fxhash = "0.2.1"
# Fast HashMap without additional protection against hash attacks.

parking_lot = "0.12.5"
# Fast and compact synchronization primitives without lock poisoning.

# ======================================================================================================================

[lints.rust]
non_snake_case = "allow"
non_upper_case_globals = "allow"
non_camel_case_types = "allow"

# ======================================================================================================================

# Usage examples:
# cargo run --example simple

[[example]]
name = "simple"
path = "examples/simple.rs"

# ======================================================================================================================

# Testing:
# cargo test

# ======================================================================================================================

# Clippy debugging:
# cargo clippy

[lints.clippy]
unused_unit = "allow"
option_if_let_else = "allow"
collapsible_if = "allow"
too_long_first_doc_paragraph = "allow"
nursery = { level = "warn", priority = -1 } # At the very bottom

# ======================================================================================================================