[package]
name = "chillffi"
version = "0.1.0"
edition = "2024"

# ======================================================================================================================

[dependencies]
bincode = { version = "2.0.1", features = ["serde"] }
# Используется для FFI; (3.0 если что - нет).

libloading = { version = "0.9.0" }
# Используется для динамической загрузки библиотек (libraryPath) 
# и получения указателей на функции (methodName), которые затем вызываются.

libffi = { version = "5.1.1" }
# Предоставляет динамический вызов C-функций с произвольной сигнатурой 
# (количество и типы аргументов, тип возврата) во время выполнения. 
# В отличие от статически зашитых обёрток, libffi позволяет конструировать 
# вызов на лету на основе описания типов, что хорошо для FFI.

libc = { version = "1.0.0-alpha.3" }
# Предоставляет системные вызовы dup2/dup для временного 
# перенаправления stdout → stderr, изолируя вывод библиотеки от служебного канала.

serde = { version = "1.0.228", features = ["derive"] }
# Сериализация и десериализация структур запросов и ответов

ctor = "1.0.13"
# Выполнение функций при старте процесса для автоматической инициализации

fxhash = "0.2.1"
# Быстрый HashMap без дополнительной защиты от атак на хеширование

# ======================================================================================================================

[lints.rust]
non_snake_case = "allow"
non_upper_case_globals = "allow"
non_camel_case_types = "allow"

# ======================================================================================================================

# Примеры работы:
# cargo run --example simple

[[example]]
name = "simple"
path = "examples/simple.rs"

# ======================================================================================================================

# Тестирование:
# cargo test

# ======================================================================================================================

# Отладка clippy:
# cargo clippy

[lints.clippy]
unused_unit = "allow"
option_if_let_else = "allow"
collapsible_if = "allow"
nursery = { level = "warn", priority = -1 } # В самом низу

# ======================================================================================================================